### PR TITLE
#158792524 Design Mockups

### PR DESCRIPTION
**Pull request by Rwothoromo**
#### What does this PR do?
Add design wireframes for the Developer listing application.

#### Description of Task to be completed?
Add the following page designs:
- Developers list
- Developer profile
- Share profile

#### How should this be manually tested?
Visit the design links on the ReadMe or visit https://xd.adobe.com/view/29abd095-a127-41b9-49bf-aaecbbc9f0ad-5f9a/

#### Any background context you want to provide?
The application design will be created based on the wireframes.

#### What are the relevant pivotal tracker stories?
[#158792524](https://www.pivotaltracker.com/story/show/158792524)

#### Screenshots (if appropriate)?
image

### CODE REVIEW

**Comment by idrisadetunmbi** [comment]
These designs are dope, my only worry is they are designed based on an iOS interface. Would you be able to port them to an actual implementation on Android?
Alternatively, you can do something similar but that is close to what can be implemented using Material  Design in Android.

**Comment by Rwothoromo** [comment]
Thank you for the feedback @idrisadetunmbi,

I see the design difference, especially to do with the buttons and above the app bar. Let me tweak it a little bit and make an update.

**Comment by Rwothoromo** [comment]
developers listing
@idrisadetunmbi I have updated the design as per the attached screenshot.

**Comment by idrisadetunmbi** [comment]
This looks really nice @Rwothoromo. If you are able to implement this in the actual design, then you probably would have the best design so far since this level up project started. 🥇 

I think you can merge this PR now and continue work with day 2.

Please take note that you might still have to tweak the thumbnails a bit as the project progresses, e.g. by using a card view per thumbnail and listing them in a grid view.

**Comment by Rwothoromo** [comment]
Thank you @idrisadetunmbi, this is good! The design will definitely evolve accordingly.

**Pull request merged**
